/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: a54e463703f9a05e3d7be7b7ba45a3f8)
declare namespace Cloudflare {
	interface Env {
		DB: D1Database;
		AI: Ai;
	}
}
interface Env extends Cloudflare.Env {}
